### ISSUE TITLE
Chests with different types of the same item do not sort.

### ISSUE THREAD

**Issue by Dinith21** [borknbeans/LightweightInventorySorting#9] opened 2024-08-05 12:40 UTC
Hi,

I've found an issue where when sorting a chest/inventory that has two or more of the same items in it, the sorter does not work properly. For example, when sorting potions that are of the same type (potion effect) but have different effect durations, the sorter does not work. The same applies to tipped arrows, and decorated pots with different patterns, and potential others.

Great mod though!

**Comment by borknbeans** [comment] 2024-08-06 19:01
Thanks for taking the time to point this out, ill take a look into it

**Comment by borknbeans** [comment] 2024-08-06 23:21
Ive narrowed down the cause. Looks like my logic for combining like items was trying to combine these items because they are technically the "same" and this later led to issues when sorting. Thanks for pointing it out!

**Comment by borknbeans** [comment] 2024-08-06 23:42
This has been fixed and will be included in the next release. Thanks again!

**Closed by borknbeans** 2024-08-06 23:42 UTC
Labels: bug
